batch_size: 16
generation: null
logging:
  output_dir: null
parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
tasks:
  custom_tasks: lighteval.tasks.multilingual.tasks
  dataset_loading_processes: 16
  max_samples: 1000
  multichoice_continuations_start_space: null
  num_fewshot_seeds: null
  tasks: lighteval|agieval_zho_cf|0|1,lighteval|ceval_zho_cf|0|1,lighteval|cmmlu_zho_cf|0|1,lighteval|m3exams_zho_cf|0|1,lighteval|belebele_zho_Hans_cf|0|1,lighteval|c3_zho_cf|0|1,lighteval|cmrc2018_zho|0|1,lighteval|chinese_squad_zho|0|1,lighteval|xcodah_zho_cf|0|1,lighteval|xcopa_zho_cf|0|1,lighteval|xcsqa_zho_cf|0|1,lighteval|mlmm_hellaswag_zho_cf|0|1,lighteval|ocnli_zho_cf|0|1,lighteval|xwinograd_zho_cf|0|1,lighteval|xstory_cloze_zho_cf|0|1