batch_size: 16
generation: null
logging:
  output_dir: null
parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
tasks:
  custom_tasks: lighteval.tasks.multilingual.tasks
  dataset_loading_processes: 16
  max_samples: 1000
  multichoice_continuations_start_space: null
  num_fewshot_seeds: null
  tasks: lighteval|mlmm_arc_dan_cf:challenge|0|1,lighteval|mlmm_hellaswag_dan_cf|0|1,lighteval|belebele_dan_Latn_cf|0|1