batch_size: 16
generation: null
logging:
  output_dir: null
parallelism:
  dp: 4
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
tasks:
  custom_tasks: /path/to/smollm/text/evaluation/tasks.py # Clone https://github.com/huggingface/smollm/ and change the path
  dataset_loading_processes: 16
  max_samples: 1000
  multichoice_continuations_start_space: null
  num_fewshot_seeds: null
  tasks: custom|hellaswag|0|1,custom|arc|0|1,custom|piqa|0|1,custom|mmlu|0|1,custom|commonsense_qa|0|1,custom|trivia_qa|0|1,custom|winogrande|0|1,custom|openbook_qa|0|1